//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by scr4edit.rc
//
#define IDD_ABOUTBOX                    100
#define IDS_PROPSHT_CAPTION             102
#define IDD_PROTOPAGE1                  103
#define IDD_PROTOPAGE2                  104
#define IDB_SPLASH                      105
#define CG_IDR_POPUP_SCR4EDIT_VIEW      106
#define IDR_MAINFRAME                   128
#define IDR_SCR4TYPE                    129
#define IDD_OBJECTS                     130
#define IDD_CLASSEDIT                   131
#define IDD_CLASSLIST                   132
#define IDD_OBJECTSEDIT                 133
#define IDD_NAMEDESC                    134
#define IDD_FRAMELIST                   139
#define IDD_FRAMEEDIT                   141
#define IDD_MESSAGEBOX                  142
#define IDD_OBJSWIZ                     143
#define IDD_TAGEDIT                     146
#define IDD_TAGLIST                     147
#define IDD_PROTOPAGE3                  148
#define IDD_EDITLOCAL                   149
#define IDD_PROTOPAGE4                  150
#define IDD_MOVELEVEL                   151
#define IDR_SCRIPT_POPUP                152
#define IDD_OBJECTS2                    153
#define IDD_TAGEDIT2                    154
#define IDD_DINTARRAY                   162
#define IDD_DINT                        163
#define IDD_DINTALL                     164
#define IDD_DEXTRAMODE                  165
#define IDD_EXPORTPAL                   166
#define IDD_PROTOPAGE5                  167
#define IDD_DBPAGE1                     168
#define IDD_DBPAGE3                     170
#define IDD_DBPAGE2                     172
#define IDD_DBPAGE4                     173
#define IDD_PROTOPAGE6                  174
#define IDC_ADD                         1001
#define IDC_EDIT                        1004
#define IDC_DUPLICATE                   1005
#define IDC_ELABEL                      1006
#define IDC_CSYSTEM                     1007
#define IDC_LIST                        1010
#define IDC_BADD                        1011
#define IDC_BDELETE                     1012
#define IDC_BCLOSE                      1013
#define IDC_BEDIT                       1014
#define IDC_CVALUE                      1015
#define IDC_CCLASS                      1018
#define IDC_CFRAMESET                   1019
#define IDC_CTRIGGER                    1020
#define IDC_ENAME                       1023
#define IDC_CBASEFRAME                  1024
#define IDC_COBJECTKEY                  1025
#define IDC_CANIMATE                    1027
#define IDC_ETITLE                      1029
#define IDC_CLOSE                       1035
#define IDC_BUPDATEALL                  1039
#define IDC_EFILENAME                   1042
#define IDC_BROWSE                      1043
#define IDC_BBROWSE                     1046
#define IDC_BNEW                        1048
#define IDC_CMOVESPEED                  1053
#define IDC_CANISPEED                   1054
#define IDC_ECONTENT                    1056
#define IDC_CAIM                        1066
#define IDC_CPTS                        1067
#define IDC_CSOUND                      1068
#define IDC_CPROTO                      1069
#define IDC_CUSERTAG                    1069
#define IDC_CCHSOUND                    1071
#define IDC_CCHPROTO                    1072
#define IDC_CDAMAGES                    1076
#define IDC_CHITPOINTS                  1077
#define IDC_CIGNORESTOPS                1078
#define IDC_CREBIRTHS                   1079
#define IDC_CDELAY                      1080
#define IDC_CPOWERLEVEL                 1081
#define IDC_CTRIGGERKEY                 1084
#define IDC_CSUBCLASS                   1085
#define IDC_EOBJECT                     1087
#define IDC_ECLASS                      1088
#define IDC_C80                         1090
#define IDC_C40                         1091
#define IDC_C20                         1092
#define IDC_C10                         1093
#define IDC_CAUTO_CHTIME                1094
#define IDC_CAUTO_CHPROTO               1095
#define IDC_CAUTO_FIRETIME              1096
#define IDC_CAUTO_BULLET                1097
#define IDC_CAUTO_STIME                 1098
#define IDC_CAUTO_SOUND                 1099
#define IDC_CAUTO_TRIGGERTIME           1101
#define IDC_CAUTO_CALLTRIGGER           1102
#define IDC_COMBO1                      1105
#define IDC_CNOTSHOWN                   1106
#define IDC_COMBO2                      1106
#define IDC_CB_SIGNSSET                 1106
#define IDC_CHECK2                      1107
#define IDC_COMBO3                      1107
#define IDC_CCONTINUITY                 1107
#define IDC_CB_POINTSOBL                1107
#define IDC_LISTLEVELS                  1108
#define IDC_COMBO4                      1108
#define IDC_CBMAXHP                     1108
#define IDC_CBEFORE                     1109
#define IDC_CAFTER                      1110
#define IDC_LISTOBJECTS                 1111
#define IDC_BINSERT                     1120
#define IDC_BDUPLICATE                  1125
#define IDC_CINT                        1127
#define IDC_BMORE                       1128
#define IDC_BPATH                       1129
#define IDC_BPROTO                      1134
#define IDC_RMODE1                      1136
#define IDC_RADIO2                      1137
#define IDC_EDIT1                       1138
#define IDC_RMSDOS                      1139
#define IDC_FORMATGROUP                 1141
#define IDC_RJASC                       1142
#define IDC_BENABLE                     1143
#define IDC_CCHANGE                     1144
#define IDC_CCHANGEPLR                  1146
#define IDC_ECHANGEDELAY                1148
#define IDC_ECHAGEPLYDELAY              1149
#define IDC_CEXTSOUND                   1150
#define IDC_EEXTSOUNDDELAY              1152
#define IDC_CHECK1                      1154
#define IDC_CINHERITPLROBJ              1154
#define IDC_CHECK3                      1158
#define IDC_C_ATLEVEL_RESETHP           1158
#define IDC_EDIT2                       1159
#define IDC_ELEVEL_HEI                  1159
#define IDC_CHECK4                      1161
#define IDC_CRESIZELEVEL                1161
#define IDC_COMBO5                      1162
#define IDC_CDEFPLROBJ                  1162
#define IDC_CHECK5                      1163
#define IDC_CFORCEDEFOBJ                1163
#define IDC_CBLIVES                     1164
#define IDC_CBMAXLIVES                  1165
#define IDC_CBHP                        1166
#define IDC_C_ATDEATH_RESETHP           1167
#define IDC_C_ATDEATH_RESETLEV          1168
#define IDC_ELEVEL_LEN                  1169
#define IDC_CB_SIGNSOBL                 1170
#define IDM_INSERTLEVEL                 32779
#define IDM_PREVIOUSLEVEL               32780
#define IDM_NEXTLEVEL                   32781
#define IDM_DELETELEVEL                 32783
#define IDM_DUPLICATELEVEL              32784
#define IDM_INSERTFRAMES                32786
#define IDM_UPDATEFRAMES                32787
#define IDM_PROTOEDITOR                 32788
#define IDM_INSERTOBJECT                32789
#define IDM_DELETEOBJECT                32790
#define IDM_DUPLICATEOBJECT             32791
#define ID_VIEW_SAVESETTINGS            32792
#define IDM_CLASSEDIT                   32793
#define IDM_UP                          32794
#define IDM_DOWN                        32795
#define IDM_LEFT                        32796
#define IDM_RIGHT                       32797
#define IDM_ADDNEWLEVEL                 32798
#define IDM_EDITLOCAL                   32799
#define IDM_UPX                         32800
#define IDM_DOWNX                       32801
#define IDM_LEFTX                       32802
#define IDM_RIGHTX                      32803
#define IDM_LEVELPROPERTIES             32804
#define IDM_BRINGTOFRONT                32805
#define IDM_SENDTOBACK                  32806
#define IDM_SELECTION                   32807
#define IDM_SAVESETTINGS                32808
#define IDM_INSERTLEVELAFTER            32809
#define IDM_REMOVEALL                   32810
#define IDM_DRAWATTRIBUTS               32811
#define IDM_DECBKCOLOR                  32812
#define IDM_INCBKCOLOR                  32813
#define IDM_DEFAULTBKCOLOR              32815
#define IDM_INFORMATION                 32817
#define IDM_EXPORT_DECLARATIONS         32819
#define IDM_EXPORT_DIAGNOSTIC           32820
#define IDM_PLUS                        32821
#define IDM_MINUS                       32822
#define IDM_EXPORTCLASS                 32824
#define IDM_EXPORT_CLASS                32825
#define IDM_FRAMEEDIT                   32826
#define IDM_IMPORTCLASS                 32828
#define ID_VIEW_UPDATEDATA              32829
#define IDM_AUTO_UPDATEDATA             32829
#define IDM_IMPORT_CLASS                32830
#define IDM_OBJECTSWIZARD               32831
#define IDM_POINTS                      32832
#define IDM_SOUNDS                      32833
#define IDM_USERDEFS                    32835
#define IDM_TAGSACTIONS                 32836
#define IDM_MOVELEVEL                   32837
#define IDM_HOME                        32838
#define ID_POPUP_EDITCLASS              32841
#define IDM_TEST123                     32842
#define IDM_LOADSORTDATA                32845
#define IDM_SAVESORTDATA                32846
#define IDM_APPLYSORTDATA               32847
#define IDM_EDITSORTDATA                32848
#define IDM_CLEAR_SORT_DATA             32849
#define IDM_EDITSYSPATHS                32850
#define IDM_GAMMACORRECTION             32851
#define IDM_EXPORTPAL                   32852
#define IDM_IMPORTPAL                   32854
#define IDM_HI_LITE_SELECTION           32855
#define IDM_DRAW_ATTRIBUTS              32856
#define IDM_RESETPAL                    32857

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        174
#define _APS_NEXT_COMMAND_VALUE         32858
#define _APS_NEXT_CONTROL_VALUE         1171
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
