//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Script1.rc
//
#define ID_OK                           1
#define ID_ABORT                        2
#define ID_CANCEL                       4
#define IDI_ICON1                       101
#define IDI_ICON2                       102
#define IDI_LITTLE_GIRL                 102
#define IDB_BITMAP1                     103
#define IDB_REDBALL                     104
#define IDR_MENU1                       105
#define IDD_ALERTE1                     107
#define IDI_ICON3                       108
#define IDR_ACCELERATOR1                109
#define IDI_ICON4                       110
#define IDB_OK                          111
#define IDB_FLOWERS                     112
#define IDB_BALLS                       113
#define IDD_APROPOSDE                   114
#define IDB_TREE1                       115
#define IDD_ALERTE2                     115
#define IDB_BITMAP2                     117
#define IDI_ICON6                       118
#define IDI_ICON5                       119
#define IDI_CHILD                       120
#define ACC1                            121
#define IDD_FatalReadDefaultWin         121
#define IDD_TEST                        123
#define IDI_ICON7                       123
#define IDI_ICON8                       124
#define IDI_ICON9                       127
#define IDD_COLOR                       129
#define IDD_COLORPROP                   129
#define IDD_OBJECTPROP                  130
#define IDD_DIALOG1                     131
#define IDC_PEN                         136
#define IDC_PEN96                       136
#define IDD_ALERTE                      154
#define IDC_SCROLLRED                   1000
#define IDC_SCROLLGREEN                 1001
#define IDC_SCROLLBLUE                  1002
#define IDC_EDIT1                       1018
#define IDC_EDIT                        1018
#define IDC_GROUP_CLASS                 1028
#define IDC_CLASS_BACKGROUND            1050
#define IDC_CLASS_BRICK                 1051
#define IDC_CLASS_DRONE                 1052
#define IDC_CLASS_POISON                1053
#define IDC_CLASS_SLIME                 1054
#define IDC_CLASS_BULLET                1055
#define IDC_CLASS_DOOR                  1056
#define IDC_CLASS_KEY                   1057
#define IDC_CLASS_ROBOT                 1058
#define IDC_CLASS_HEALING               1059
#define IDC_CLASS_GOAL                  1060
#define IDC_CLASS_PLAYER                1061
#define IDC_CLASS_TRESOR                1062
#define IDC_TAB1                        1064
#define KEY_UP                          2001
#define KEY_LF                          2002
#define KEY_RG                          2003
#define KEY_PGUP                        2010
#define KEY_PGDN                        2011
#define KEY_DN                          2012
#define KEY_ESC                         2014
#define KEY_DELETE                      2015
#define KEY_END                         2016
#define KEY_HOME                        2017
#define KEY_INSERT                      2018
#define ID_FICHIER_NOUVEAU              40001
#define ID_FICHIER_OUVRIR               40002
#define ID_FICHIER_FERMER               40003
#define ID_FICHIER_ENREGISTRER          40004
#define ID_FICHIER_ENREGISTRERSOUS      40005
#define ID_FICHIER_IMPORTERIMAGE        40006
#define ID_FICHIER_EXPORTERIMAGE        40007
#define ID_DITION_COPIER                40008
#define ID_EDITION_COPIER               40008
#define ID_DITION_COLLER                40009
#define ID_EDITION_COLLER               40009
#define ID_DITION_NOUVELLEIMAGE         40010
#define ID_OPTION_ROTATION90            40011
#define ID_OPTION_FLIPVERTICAL          40012
#define ID_OPTION_FLIPHORIZONTAL        40013
#define ID_OPTION_REDIMENSIONNER        40014
#define ID_OPTION_ENLARGER2X            40015
#define ID_OPTION_AGRANDIR2X            40015
#define ID_EDITION_COUPER               40016
#define ID_AIDE_DOCUMENTATIONTECHNIQUE  40017
#define ID_FICHIER_QUITTER              40018
#define ID_AIDE_DITEUR                  40019
#define ID_AIDE_PROPOSDE                40020
#define ID_OPTION_AUTOMAPPING           40022
#define KEY_C                           40023
#define ID_IMAGE_PRECEDENTE             40025
#define ID_IMAGE_SUIVANTE               40026
#define ID_IMAGE_EFFACER                40028
#define ID_IMAGE_SUPPRIMER              40029
#define ID_IMAGE_INSERER                40037
#define ID_IMAGE_PROPRIETE              40038
#define ID_OBJET_PROPRIETE              40039

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         40040
#define _APS_NEXT_CONTROL_VALUE         1068
#define _APS_NEXT_SYMED_VALUE           111
#endif
#endif
